### ISSUE TITLE
Error in connectionpool.py

### ISSUE THREAD

**Issue by txivo83** [rmblake/check_mk-slack#19]
Im getting errors sending notifications using this script. I've installed dependencies (requests) but still getting this error. Any idea how I can fix it?

2020-02-28 12:12:04 Executing 1 notifications:
2020-02-28 12:12:04   * notifying slack via slack, parameters: general, bulk: no
2020-02-28 12:12:04      executing /omd/sites/SAURON/share/check_mk/notifications/slack
2020-02-28 12:12:04      Output: Traceback (most recent call last):
2020-02-28 12:12:04      Output:   File "/omd/sites/SAURON/share/check_mk/notifications/slack", line 7, in <module>
2020-02-28 12:12:04      Output:     import requests
2020-02-28 12:12:04      Output:   File "/omd/sites/SAURON/local/lib/python/requests/__init__.py", line 43, in <module>
2020-02-28 12:12:04      Output:     import urllib3
2020-02-28 12:12:04      Output:   File "/omd/sites/SAURON/local/lib/python/urllib3/__init__.py", line 7, in <module>
2020-02-28 12:12:04      Output:     from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
2020-02-28 12:12:04      Output:   File "/omd/sites/SAURON/local/lib/python/urllib3/connectionpool.py", line 100
2020-02-28 12:12:04      Output:     _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
2020-02-28 12:12:04      Output:                                     ^
2020-02-28 12:12:04      Output: SyntaxError: invalid syntax
2020-02-28 12:12:04      Plugin exited with code 1

**Comment by txivo83** [comment]
I bypassed this error setting interpreter like this: #!/omd/sites/SITENAME/bin/python
